### ISSUE TITLE
Error when using AdaptiveCard from Flow in Teams

### ISSUE THREAD

**Issue by tposzytek** [microsoft/AdaptiveCards#2924]
# Platform

* Teams, 
* Flow

# Author or host

AdaptiveCard is being returned as a parameter by the "Create Approval (V2)" action in Flow. I am then trying to post it using "Post your own adaptive card as the Flow bot to channel" and that works. However, when trying to respon

# Version of SDK

No idea

# Issue

AdaptiveCard is being returned as a parameter by the "Create Approval (V2)" action in Flow. I am then trying to post it using "Post your own adaptive card as the Flow bot to channel" and that works. However, when trying to respond to it Card display error: "Unable to reach app. Please try again." and when I use Fiddler to check the traffic I see error 502 Bad Gateway and message: {"errorCode":1008,"message":"<BotError>Error when sending request to bot"}

This is how it looks like:
![image](https://user-images.githubusercontent.com/50657947/57763251-4e123700-7701-11e9-8143-1a4b10ae7e73.png)

What is wrong? A known issue? How can be solved?

**Comment by shalinijoshi19** [comment]
Thanks for reporting @tposzytek ; We are following up offline wiht the flow partners and will circle back once we know more. PS: thanks for including hte Fiddler snapshot with the response headers + body!

**Comment by tposzytek** [comment]
If you need any information from me, just ask ;) I will gladly help!

**Comment by PhilippHeider** [comment]
have the same issue!

**Comment by shalinijoshi19** [comment]
Hey guys 
Apologies for not responding sooner. But looks like @tposzytek/ @PhilippHeider the scenario you are attempting is unsupported at the moment. Please see the response below: David (dblyth-msft) from our Flow integration partner team:

> Turns out the user is not doing something supported … yet. 

> The first thing to note is that Teams does not support posting directly to HTTP endpoints as part of a card … they only send the response back to the Bot that originated the message. 
> 
> It appears that the customer is not sending the card that Flow generates for the approval. In actuality he’s building a totally custom card that *LOOKS* a lot like (and was probably based on) the card we generate in Flow Approvals. But he’s made changes to it, including to the structure/schema. We receive the response from the bot and return a 400 Bad Request because the payload is malformed from our expectations of the card we generated.
> 
> The fully-custom / interactive card is a scenario we have on our radar. 

> -- <cite>David @dblyth-msft </cite>

**Comment by vishmonne** [comment]
hi guys , i am getting the same issue @tposzytek
![team_error](https://user-images.githubusercontent.com/10339913/59566673-d4af9080-9080-11e9-9260-269bbf088de2.PNG)
  mentioned . PFA the screenshot for reference

**Comment by tposzytek** [comment]
Yes, the issue persist. I'm using just the card returned by the Flow assign task action. Not a custom one. We had this discussion with Daniel Laskewitz recently and his opinion is that this is permissions related issue, as he somehow succeeded in assigning a task to himself, posting a card to Teams and approving this way. But if assigned to someone else, it fails.

Best regards,
Tomasz Poszytek

________________________________

**Comment by tposzytek** [comment]
All! The error I rised has been solved by Microsoft circa 3 weeks ago. I am closing this issue.

**Comment by johno-absa** [comment]
> All! The error I rised has been solved by Microsoft circa 3 weeks ago. I am closing this issue.

We are still experiencing the issue. Would it be possible to post your adaptive card json here?

The problem w are facing is that the flow does not wait for input from the user(completing the adaptive card) when using a custom adaptive card, so the flow completes almost immediate and then when the user clicks on the custom adaptive card the "Unable to reach app. Please try again" is shown on the card.

**Comment by Basavarajsk** [comment]
Hi Guys, I am getting same error.
![image](https://user-images.githubusercontent.com/24410864/62536063-9d808300-b86a-11e9-9700-a8324461df8f.png)

**Comment by RajaniJillaGit** [comment]
Hi Team,

We are facing the same issue where we have an adaptive card and post back button which calls an external API while we wait for the API to respond, teams is giving this error. Could you please help on this issue as it is a road block for the feature to be able to release ?

**Comment by Raghavva-245** [comment]
@tposzytek i'm also having same issue in my environment. can you please let me know how i can fix that? 

![image](https://user-images.githubusercontent.com/66309003/83512952-98925d00-a496-11ea-8133-69b851d75eb7.png)

**Comment by tposzytek** [comment]
Hi @Raghavva-245 - so there is no solution for this action. Switch to using "Post an Adaptive Card to Microsoft Teams channel and wait for response" to be able to get back the submitted form. With the previous action: "Post your own Adaptive Card to Microsoft Teams channel" it will not work.

**Comment by Raghavva-245** [comment]
@tposzytek - where do we change those options? actually i am using Microsoft Forms in Teams, using that i have created a Poll in one of my Teams channel. so when participants are submitting the polls they are getting the error "Unable to Reach App, Please try again".
