### ISSUE TITLE
[MS Teams] [Adaptive Cards] [Multiline input text does not allow explicit break line from the user]

### ISSUE THREAD

**Issue by SMichalet** [microsoft/AdaptiveCards#5086]
# Platform
What platform is your issue or question related to? (Delete other platforms).

- [ ] Windows - MS Teams

# Details

Hi teams !

I am trying to do a simple adaptive card which contains a multiline input text.

The json card : 
```json
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.2",
  "body": [
    {
      "type": "TextBlock",
      "size": "Medium",
      "weight": "Bolder",
      "text": "Record creation",
      "horizontalAlignment": "Center"
    },
    {
      "type": "TextBlock",
      "text": "Description",
      "size": "Medium",
      "weight": "Bolder"
    },
    {
      "type": "Input.Text",
      "isMultiline": true,
      "id": "desc",
      "isVisible": true
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Send",
      "data": {
        "action": "OK"
      }
    },
    {
      "type": "Action.Submit",
      "title": "Cancel",
      "data": {
        "action": "CANCEL"
      }
    }
  ]
}
```

In the visualizer, I can correctly break the lines in the input by pressing Enter.

![image](https://user-images.githubusercontent.com/2147094/99370660-42876980-28be-11eb-8ab4-14b5a995e8d2.png)

On MS Teams with the same json card, the input is displayed with a grey overlay.
The break lines occur automatically when the current line is full but we cannot explicitly break the line by pressing Enter.

![image](https://user-images.githubusercontent.com/2147094/99370615-30a5c680-28be-11eb-95f2-1beadf6e828f.png)

But if I try to copy paste some text with break lines in it, it works.
That is really counter intuitive here for a user to not be able to make break lines manually in a multiline input of text.

The same thing happens with directional keys. The left/right ones are working but not the up/down.

Hope I am in the right place.
Thanks !

**Comment by dclaux** [comment]
@SMichalet I cannot repro this in Teams - with that same card, if I press Enter, I get a new line. This might have been a bug that is now fixed.

@siduppal bringing this to your attention.

**Comment by baole** [comment]
@dclaux our customer reported this issue. Today I tested it on different apps, if I pressed Enter
- I got a new line in Teams native app/Mac OS
- No effect in Teams/Web App/Chrome/Mac OS
- No effect in Teams/Web App/Edge/Mac OS

It definitely doesn't work on browsers.

**Comment by dclaux** [comment]
I have tested with the AC JS SDK and cannot repro this. This is a Teams issue, please reach out to Teams support.

**Comment by baole** [comment]
Just for information, I use REST API and here is my response to a dialog "invoke"

```
{
  "task": {
    "type": "continue",
    "value": {
      "title": "Enter your standup for General",
      "width": "large",
      "height": "large",
      "card": {
        "content": {
          "body": [
            {
              "text": "What did you do yesterday?",
              "weight": "bolder",
              "isRequired": false,
              "type": "TextBlock"
            },
            {
              "id": "0",
              "isMultiline": true,
              "maxLength": 5000,
              "placeholder": "Enter text",
              "isRequired": true,
              "type": "Input.Text"
            },
            {
              "text": "What will you do ?",
              "weight": "bolder",
              "isRequired": false,
              "type": "TextBlock"
            },
            {
              "id": "1",
              "isMultiline": true,
              "maxLength": 5000,
              "placeholder": "Enter text",
              "isRequired": true,
              "type": "Input.Text"
            },
            {
              "text": "Are there any impediments in your way?",
              "weight": "bolder",
              "isRequired": false,
              "type": "TextBlock"
            },
            {
              "id": "2",
              "isMultiline": true,
              "maxLength": 5000,
              "placeholder": "Enter text",
              "isRequired": true,
              "type": "Input.Text"
            }
          ],
          "actions": [
            {
              "title": "Submit",
              "data": {
                "action": "dialog_submission",
                "skey": "2020-11-27",
                "pid": "99",
                "pstad": "0",
                "sid": "44"
              },
              "type": "Action.Submit"
            }
          ],
          "type": "AdaptiveCard",
          "version": "1.0",
          "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
        },
        "contentType": "application/vnd.microsoft.card.adaptive"
      }
    }
  }
}
```

Which rendered as below screenshot:

![image](https://user-images.githubusercontent.com/1460168/100413110-cdaeef00-3076-11eb-8c39-2646d77f0a9e.png)

The dialog works perfectly with Enter key on native Mac OS app, but doesn't work on any browsers

**Comment by shalinijoshi19** [comment]
Hey @siduppal bringing this to your attention for helping out on the Teams side pls? Thanks!

**Comment by siduppal** [comment]
There was a recent bug introduced impacting this functionality which has been addressed and the fix is rolling out.

**Comment by udaya-reddy** [comment]
any update on this bug?
Teams native also does not support enter on multiline text box in adaptive cards...

**Comment by Trinetra-MSFT** [comment]
@udaya-reddy : I will check the status and get back to you.

**Comment by udaya-reddy** [comment]
Adaptive card version used : 1.2 btw

Attached are the images... web / directline  is fine... but the teams channel has support issue for multiline adaptive card text box.

Web version of teams.
![image](https://user-images.githubusercontent.com/67152550/103892488-ae918b80-5111-11eb-837a-729148f534f3.png)

Native App version
![image](https://user-images.githubusercontent.com/67152550/103892512-bc471100-5111-11eb-9df4-6c957fb688ea.png)

Directline channel version on web...
![image](https://user-images.githubusercontent.com/67152550/103892555-ca952d00-5111-11eb-8570-1e3f4d8855cd.png)

**Comment by Mallipriya-MSFT** [comment]
@udaya-reddy, Bug is resolved and It is working as expected on our side for both native and web Teams App.

**Comment by baole** [comment]
@Mallipriya-MSFT I just tested on Chrome browser/Mac OS, press enter key "Input.Text" block on a popup dialog doesn't break into new line. I doubt the issue was't resolve on Chrome browser/Mac OS

**Comment by udaya-reddy** [comment]
I also just tested in native teams... it does not break into new line.. yes tested on chrome browser.
Not sure if we need to update any software or library to get the latest fix.

**Comment by Mallipriya-MSFT** [comment]
@udaya-reddy, I have tested in the public range as well and it works fine. Can you check once again with latest version of browser and let us know.

**Comment by baole** [comment]
@Mallipriya-MSFT confirmed on Chrome browser/Mac OS. Thanks!

**Comment by udaya-reddy** [comment]
@Mallipriya-MSFT yes. it seems fixed now... Not sure what did the trick...  Any software update made?

**Comment by Mallipriya-MSFT** [comment]
@udaya-reddy, Bug got resolved but not with software changes.

**Comment by cleans2002** [comment]
Has this solved the problem?
I am still experiencing this problem on Teams Desktop.

Adaptive cards are as follows.
-----------------------------
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "ColumnSet",
                    "columns": [
                        {
                            "type": "Column",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "weight": "Bolder",
                                    "text": "Description",
                                    "wrap": true,
                                    "horizontalAlignment": "Center"
                                },
                                {
                                    "type": "Input.Text",
                                    "id": "update_description",
                                    "isMultiline": true,
                                    "value": "${title}"
                                }
                            ],
                            "width": "stretch"
                        }
                    ]
                }
            ]
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Submit",
            "data": {
                "msteams": {
                  "type": "messageBack",
                  "displayText": "Complete"
                }
            }
        }
    ]
}
-----------------------------
Is there a solution?

**Comment by Mallipriya-MSFT** [comment]
Hi @cleans2002, It is a regression as we are able to reproduce the issue at our end. Will re-open the bug and update on the progress soon.

**Comment by gvitale1** [comment]
> Hi @cleans2002, It is a regression as we are able to reproduce the issue at our end. Will re-open the bug and update on the progress soon.

seconding this issue. Works on preview within a flow but MS Teams does not allow a line break.

**Comment by stroganovmaxv** [comment]
The similar bug is present in Desktop and Web MS Teams for `TextBlock`:
```
        {
            "type": "TextBlock",
            "text": "one\ntwo\nthree",
            "wrap": true,
            "id": "bkprCommentText"
        }
```
It looks like `one two three`

@Mallipriya-MSFT, could possibly estimate when this bug will be fixed?

**Comment by cleans2002** [comment]
> The similar bug is present in Desktop and Web MS Teams for `TextBlock`:
> 
> ```
>         {
>             "type": "TextBlock",
>             "text": "one\ntwo\nthree",
>             "wrap": true,
>             "id": "bkprCommentText"
>         }
> ```
> 
> It looks like `one two three`
> 
> @Mallipriya-MSFT, could possibly estimate when this bug will be fixed?

There is a workaround for this issue.
In MS Teams, the newline is 3 spacebars + \n.
Please give it a try.
Example : one   \ntwo   \nthree

**Comment by Mallipriya-MSFT** [comment]
The issue is resolved and we got it working at our end. Could you please test the issue of break line of text in multiline input once try from your end as well.

**Comment by cleans2002** [comment]
> The issue is resolved and we got it working at our end. Could you please test the issue of break line of text in multiline input once try from your end as well.

Unfortunately it still doesn't work at all.
My source is below.
```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.2",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "Record creation",
            "horizontalAlignment": "Center"
        },
        {
            "type": "TextBlock",
            "text": "Description",
            "size": "Medium",
            "weight": "Bolder"
        },
        {
            "type": "Input.Text",
            "isMultiline": true,
            "id": "desc",
            "isVisible": true
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Send",
            "data": {
                "action": "OK"
            }
        },
        {
            "type": "Action.Submit",
            "title": "Cancel",
            "data": {
                "action": "CANCEL"
            }
        }
    ]
}
```
This source is line breaks normally using Shift+Enter in the'Card editor' of'App Studio'.
However, after clicking the'Send me this card' button, it does not work properly in the Chatting tab.
![image](https://user-images.githubusercontent.com/41402699/110430028-19018080-80ef-11eb-9bd2-04e0e90b3f67.png)
![image](https://user-images.githubusercontent.com/41402699/110430070-2c145080-80ef-11eb-8c4b-dc48213c5f40.png)

**Comment by stroganovmaxv** [comment]
> The issue is resolved and we got it working at our end. Could you please test the issue of break line of text in multiline input once try from your end as well.

According to the type "TextBlock" the issue is still present.
Source code:
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "Container",
      "items": [
        {
          "type": "TextBlock",
          "text": "one\ntwo\nthree",
          "wrap": true
        }
      ]
    }
  ]
}
Result sent card:
![06](https://user-images.githubusercontent.com/75748513/110801509-01103500-8286-11eb-9ac9-7c4f09723aaa.jpg)

**Comment by dclaux** [comment]
@stroganovmaxv this issue is about Input.Text. If there is a problem with TextBlock, it is best to open another issue.

That said, the behavior you are seeing is by design. TextBlock is processed with Markdown, and Markdown requires two consecutive \n characters.

```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "text": "abc\n\ndef\n\nghi",
            "wrap": true
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3"
}
```
![image](https://user-images.githubusercontent.com/1334689/110822702-2e3cf300-8246-11eb-90fb-993a22ebc266.png)

**Comment by stroganovmaxv** [comment]
new issue for TextBlock type was created https://github.com/microsoft/AdaptiveCards/issues/5538
