### ISSUE TITLE
Action.OpenUrl not working in MS Teams - New meeting experience

### ISSUE THREAD

**Issue by figgsoftware** [microsoft/AdaptiveCards#5274]
# Platform

What platform is your issue or question related to? (Delete other platforms).

JavaScript

# Author

Author

If you're an author, who are you sending cards to?

MS Teams  (meeting chat)

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest main, etc...

# Details
Opening a url from an Adaptive card is not working in the Microsoft Teams New meeting experience (On Windows and Mac) and throws an error message. We use the Action.OpenUrl from the adaptive card with a url that deeplinks to a Taskdialog (https://teams.microsoft.com/l/task/d3d1be68-066c-4967-a74b-9edcf902dcfb?url=https%3A%2F%2Fapp.boarddecisions.com%2Fteams%2F%23%2Fdecision-vote%2F67998006-b0bc-4f39-9996-c33a28ce8a80%2Fitems%2F01O4DEEP74Y2IRERLYMZA23NXXU3SLONSH%2Fdecisions%2Fucdk9r25GEyp2AAxZ3TAGJYAP6WW%2Fpolls%2Fddf128d7-fac6-48c4-9b62-1a2073d83d5f%3FdriveId%3Db!kl_BfImaIECijqsxvyBmfnZ3ahPJLp5OkJLikCusoSX0unftk3fiSotfod1M4p0B%26groupId%3Db58d717f-c122-490b-8e7c-447ffce69956%26channelId%3D19%3A64b1302ab8a9426b95db7e4c8a42858b%40thread.tacv2%26tenant%3Dc7105dda-a548-4def-8ee7-e992e0e6dcb0%26realm%3Dfigg.onmicrosoft.com&height=580&width=1024&title=Cast%20vote&fallbackUrl=https%3A%2F%2Fapp.boarddecisions.com%2FGenericRedirect%3Fngapp%3Dweb%26endpoint%3Ddecision-vote%2F67998006-b0bc-4f39-9996-c33a28ce8a80%2Fitems%2F01O4DEEP74Y2IRERLYMZA23NXXU3SLONSH%2Fdecisions%2Fucdk9r25GEyp2AAxZ3TAGJYAP6WW%2Fpolls%2Fddf128d7-fac6-48c4-9b62-1a2073d83d5f%26driveId%3Db!kl_BfImaIECijqsxvyBmfnZ3ahPJLp5OkJLikCusoSX0unftk3fiSotfod1M4p0B%26groupId%3Db58d717f-c122-490b-8e7c-447ffce69956%26channelId%3D19%3A64b1302ab8a9426b95db7e4c8a42858b%40thread.tacv2%26tenant%3Dc7105dda-a548-4def-8ee7-e992e0e6dcb0%26realm%3Dfigg.onmicrosoft.com. 

If we trigger that same url from a pure link in the chat it works perfectly in the new meeting experience, so it seems it is just a small quirk with the adaptive card in the new meeting experience.

 

(https://stackoverflow.com/questions/tagged/adaptive-cards).
<img width="926" alt="vote" src="https://user-images.githubusercontent.com/17601161/104561826-fcdde780-5647-11eb-9a7e-08371f562061.png">

**Comment by shalinijoshi19** [comment]
@siduppal do you happen to have thoughts on this at all?  Is the New meeting experience different from the usual teams flow?

**Comment by Wajeed-msft** [comment]
Ack. Looking into this.

**Comment by Manish-MSFT** [comment]
@figgsoftware , Can we get on call to discuss this. Please write to us at microsoftteamsdev@microsoft.com

**Comment by figgsoftware** [comment]
Yes. I have time today @Manish-MSFT

**Comment by Manish-MSFT** [comment]
@figgsoftware , Thanks for discussing over call. I was able to repro this issue. I could get the adaptive card open url link working in meetings-chat window but meetings-live window it throws error. I am taking this forward for discussion with team, I will update you once we raise a bug.
![image](https://user-images.githubusercontent.com/70321016/104703344-3a706c80-573d-11eb-991f-3b5f5b50b661.png)

**Comment by figgsoftware** [comment]
Great job!

**Comment by Manish-MSFT** [comment]
@figgsoftware , Just an update : The issue is being investigated by engineering team now, I will keep you updated with latest responses from their end.

**Comment by Manish-MSFT** [comment]
@figgsoftware , Update: a bug has been filed against this issue.

**Comment by figgsoftware** [comment]
What is the status here? This is super urgent. It worries me that the v21.01 was removed and then the Short Term was added :) @RebeccaAnne @Manish-MSFT

**Comment by RebeccaAnne** [comment]
Since this appears to be a Teams bug rather than an Adaptive Cards issue directly, I moved it out of 21.01 since it won't ship in that (or any) Adaptive Cards release. The fix will come on the Teams side, as tracked by the teams bug mentioned above. @Manish-MSFT may be able to give you updated status from their end.

**Comment by Manish-MSFT** [comment]
@figgsoftware  : We have already escalated the issue to be fixed sooner. I will update you once I get any further information on this ticket.

**Comment by susanshen96** [comment]
Hi @figgsoftware - I'm trying to repro this issue so I can debug properly, but have not had success in doing so - I copied the link to an adaptive card with an open URL button, but was able to open the task module successfully. Just a couple questions: 

1. I was made aware that this was occurring when a card is copied from a channel and pasted into the meeting. Is this the only case in which occurs, or is it happening with all Decisions cards?
2. What are the repro steps in order to get a card to be shared in a meeting chat? I'm not familiar with Decisions, so some documentation would be helpful.

**Comment by figgsoftware** [comment]
@susanshen96 This happens when the adaptive card is posted or copied into the meeting chat. It fails when you have the meeting window open in the new meeting experience and try to click the button. It works fine if you are not inside the meeting window.

**Comment by figgsoftware** [comment]
@susanshen96 When I say "posted"....we actually post the adaptive card via the Microsoft Graph  API.

**Comment by figgsoftware** [comment]
![image](https://user-images.githubusercontent.com/17601161/109565366-a4bd5080-7ae2-11eb-8b08-ef3a8013f5e5.png)
@susanshen96

**Comment by susanshen96** [comment]
Thanks @figgsoftware - was able to get a repro - I'll circle back with what I find.

**Comment by susanshen96** [comment]
Hi @figgsoftware - updates on my investigation: this seems to be an issue with GraphAPI - when a card is posted to a channel via the following method (https://docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&tabs=http#request-2) it doesn't have any app context, which is necessary in the new meeting experience for the client to be able to open the URL. I will raise this issue with the Graph team, and keep you posted on any updates I receive.

**Comment by abdulkareemnalband** [comment]
@susanshen96 
Colleague of @figgsoftware here
we are following [this](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-task-modules#task-module-deep-link-syntax) document to form URL, which contains application id of give in teams application manifest. 
And our payload for attachment is in form 
```json
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        // snipped
    ],
    "actions": [
        {
            "id": "Agenda",
            "type": "Action.OpenUrl",
            "title": "Agenda",
            "url": "https://teams.microsoft.com/l/task/<APP_ID>?url=<our_app_url>"
        }
    ]
}
```

and our payload for graph contains
```json
{
    "body": {
        "contentType": "html",
        "content": "<attachment id=\"{id}\"></attachment>"
    },
    "attachments": [
        {
            "id": "{id}",
            "contentType": "application/vnd.microsoft.card.adaptive",
            "contentUrl": null,
            "content": "{json encoded card}",
            "name": null,
            "thumbnailUrl": null
        }
    ]
}
```

where should we provide application context here

**Comment by susanshen96** [comment]
Hi @abdulkareemnalband - The issue is not with the task module URL, but with the Graph API payload which does not currently allow for app context to be sent. I am speaking to the Graph team now to see if there can be support for this, and will follow up with you when I find out.

**Comment by susanshen96** [comment]
Hi @figgsoftware / @abdulkareemnalband - a quick update - I am working on a fix for this that will not involve changing the Graph API schema. Will update you on when the fix is checked in.

**Comment by figgsoftware** [comment]
That is great news @susanshen96 ! Just had 3 different customers asking about the status today alone :)
Keep us posted.

**Comment by susanshen96** [comment]
Hi @figgsoftware - the fix has been checked in yesterday, but it will take some time (2-3 weeks) for the fix to become publicly available. I will be tracking the commit in the meantime, and will update this thread for when the fix should be available. Thank you for your patience!

**Comment by Nikitha-MSFT** [comment]
Bug is Resolved now, we have tested this at our end, could you please also check and confirm?

**Comment by figgsoftware** [comment]
@Nikitha-MSFT we are still seeing the same issue. What Teams-client version is required?

**Comment by susanshen96** [comment]
The fix has not propagated to general ring yet - it will take another 1-2 weeks to show up.

**Comment by figgsoftware** [comment]
@susanshen96  We are still not seeing the fix in our production tenant. Could you check how far out the fix has reached?

**Comment by Nikitha-MSFT** [comment]
Bug is Resolved now, we have tested this at our end, could you please also check and confirm?

**Comment by figgsoftware** [comment]
@susanshen96  @RebeccaAnne  At first it looked like the bug was resolved, but then at a closer look it looks like you have introduced a new issue or uncovered an existing one with your fix. If a person it logged into the Teams tenant with a guest user (Microsoft account or out of tenant Office 365 account ), they get a strange error message: "This action is not supported by . "
![image](https://user-images.githubusercontent.com/17601161/118554974-6ab72e80-b762-11eb-808f-0181e34fbee3.png)
