### ISSUE TITLE
[Rendering] AdaptiveCards.Templating cannot be installed due to Newtonsoft.Json version clash

### ISSUE THREAD

**Issue by JackSinclairT** [microsoft/AdaptiveCards#6212]
# Target Platform

Please list the platform(s) that your application is targeting and remove platforms you are not targeting:
- WPF

# Target Application
Teams

# Problem Description

It's impossible to add AdaptiveCards.Templating via NuGet install due to the following error:
NU1605	Detected package downgrade: Newtonsoft.Json from 12.0.3 to 11.0.2. Reference the package directly from the project to select a different version. 
 cron-test -> AdaptiveCards.Templating 1.2.1 -> AdaptiveExpressions 4.11.1 -> Newtonsoft.Json (>= 12.0.3) 
 cron-test -> AdaptiveCards.Templating 1.2.1 -> Newtonsoft.Json (>= 11.0.2 && <= 12.0.3)

It seems this is down to a newtonsoft.json version clash between AdaptiveCards.Templating (11.0.2) and one of it's dependencies AdaptiveExpressions (12.0.3).

# Screenshot

![image](https://user-images.githubusercontent.com/9784427/129565272-86f38c35-83ab-4019-b5f8-b5b01cc74024.png)

# Version of SDK
AdaptiveCards.Templating 1.2.1

**Comment by jonmill** [comment]
This should be fixed via https://github.com/microsoft/AdaptiveCards/issues/5575, please re-open if that isn't the case.

**Comment by RickDMyers** [comment]
I'm using DotNet 6 and still having the same issue:

Errror NU1605:
AdaptiveCards.Templating 1.2.2 -> AdaptiveExpressions 4.11.2 -> Newtonsoft.Json (>= 12.0.3) 

How do I resolve this issue?
