### ISSUE TITLE
[Designer] Style changes required for berlin config

### ISSUE THREAD

**Issue by licanhua** [microsoft/AdaptiveCards#6906]
Details 
1.	Attribution area:
Should look like this. The green dotted box that contains the attribution should be invisible. 
![image](https://user-images.githubusercontent.com/6290692/152872840-744d5cd0-181f-4843-b361-6e3a3a0be9ba.png)

2.
![image](https://user-images.githubusercontent.com/6290692/152873270-542a0f64-aabd-4ed8-97eb-afb08a566075.png)

3.
for the light theme large card, The attribution area is not stationary/sticky to the top of the card. when I scroll up and down in the designer, the attribution overlaps the content area

![image](https://user-images.githubusercontent.com/6290692/152873431-022c71fd-c125-4a1e-b3b4-6969f9a5cae7.png)

4. Berlin card style

A few things to change and double check on
- The dark theme card color is 2C2C2C, and light theme is F6F6F6
- Corner radius 8px
- card stroke is 000000 at 10% opacity for dark theme, 5.78% opacity for light theme. The stroke is transparent.
- Both themes need a card shadow: position x=0, y=2, blur=4, color 000000 at 6.5% opacity for light theme and color 000000 at 8% opacity for dark theme
![image](https://user-images.githubusercontent.com/6290692/152874077-6b86f006-5fc0-42cd-8229-a2283f1518dc.png)

**Comment by paulcam206** [comment]
@licanhua - Is this related to #6896 or something else?

**Comment by licanhua** [comment]
more than that. that PR only covers margin and padding. still have a bunch of things

**Comment by JeanRoca** [comment]
@anna-dingler fyi
@licanhua I think item 3 on the list has been fixed. Are there any others that were fixed as well?

I think item 1 covers fixing this:
<img width="294" alt="image" src="https://user-images.githubusercontent.com/33772802/183494191-9ca42beb-3558-496e-a034-6794856adbb1.png">

**Comment by anna-dingler** [comment]
@licanhua @JeanRoca Number 3 (stationary header) is only fixed on small and medium cards. The issue still occurs on light theme, large cards
