### ISSUE TITLE
{Linked:Bug108199}[Adaptive Card-How are you feeling today]: ‘Alt’ attribute is not defined for emotion icons control appearing on 'How are you feeling today' card.

### ISSUE THREAD

**Issue by Shireen2000** [microsoft/AdaptiveCards#7721]
### Target Platforms

Other

### SDK Version

105.0.1300.0 

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
OS: 22H2 (OS Build 25120.1000)
Browser: Edge Dev
Browser Version: Version 103.0.1255.0 (Official build) dev (64-bit)
URL: [Designer | Adaptive Cards](https://adaptivecards.io/designer/)
Screen Reader: Narrator

**Pre-requisites:**
Copy the complete json code in ''Card Payload Editor". (Please refer attachment).

**Repro Steps:**
Launch the above URL.
Navigate to header control ‘Designer’ using tab key and activate through enter key.
Navigate to emotion icon control which is appearing under How do you feeling today heading and inspect code for image using F12.
Observe the issue.

**Actual Result:**
‘Alt’ attribute is not defined for emotion icons control appearing on 'How are you feeling today' card.

**Expected Result:**
‘Alt’ attribute should be defined for emotion icons control appearing on 'How are you feeling today' card.

**Observation:**
Issue is also repro with JAWS and NVDA.

**User Experience:**
Screen reader users will not be able to know name of emotion icons if alt attribute is not defined.

**MAS Reference:**
[Non-text Content - Liquid (microsoft.com)](https://liquid.microsoft.com/Web/Object/Read/MS.Accessibility/Requirements/01.01.01)

Have feedback to share on Bugs? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0) “

### Screenshots

<img width="1005" alt="MAS1 1 1  ‘Alt’ attribute is not defined for emotion icons control appearing on 'How are you feeling today' card" src="https://user-images.githubusercontent.com/96283152/181264978-a368aab3-c685-41b9-bbaf-5adc89f5e970.png">
<img width="1005" alt="Dependent Bug 108199 attachment" src="https://user-images.githubusercontent.com/96283152/181264993-71fd6ea5-78cd-485d-83a3-ad65217087dd.png">
<img width="1005" alt="Alt text is not present for all control that have icon url" src="https://user-images.githubusercontent.com/96283152/181265005-7213e615-2894-4af4-bd8e-0d647ab065d1.png">

### Card JSON

```JSON
{
   "type": "AdaptiveCard",
   "version": "0.0",
   "body": [
      {
         "type": "ColumnSet",
         "columns": [
            {
               "type": "Column",
               "items": [
                  {
                     "type": "TextBlock",
                     "size": "small",
                     "weight": "lighter",
                     "text": "Educators see your name and reflection, classmates won’t see your name",
                     "wrap": true,
                     "spacing": "none"
                  }
               ],
               "style": "emphasis",
               "bleed": true,
               "height": "stretch"
            }
         ]
      },
      {
         "type": "TextBlock",
         "size": "large",
         "weight": "bolder",
         "text": "How are you feeling today?",
         "wrap": true
      },
      {
         "type": "TextBlock",
         "size": "small",
         "text": "By Fadi Teacher  |  Closes {date}",
         "wrap": true
      }
   ],
   "actions": [
      {
         "type": "Action.Submit",
         "data": {
            "msteams": {
               "type": "task/fetch"
            },
            "data": {
               "Type": "task/fetch"
            },
            "datajson": {
               "PostCreatorName": "Fadi Teacher",
               "PostCreatorId": "c4e6beb4-5115-408d-8965-7328b0bfc6d4",
               "ReflectId": "8fcc02d7-1506-445c-b881-10649ff556b0",
               "Action": "setFeedback",
               "ReflectPrivacyId": "AnonymousForClassmates",
               "ReflectQuestionId": "FeelingToday",
               "DueDateUtc": "2021-05-27T22:49:04.051Z",
               "ReflectFeedback": "VeryHappy"
            }
         },
         "title": " ",
         "iconUrl": "https://roravi.ngrok.io/reflectCardImages/veryHappyIcon.png"
      },
      {
         "type": "Action.Submit",
         "data": {
            "msteams": {
               "type": "task/fetch"
            },
            "data": {
               "Type": "task/fetch"
            },
            "datajson": {
               "PostCreatorName": "Fadi Teacher",
               "PostCreatorId": "c4e6beb4-5115-408d-8965-7328b0bfc6d4",
               "ReflectId": "8fcc02d7-1506-445c-b881-10649ff556b0",
               "Action": "setFeedback",
               "ReflectPrivacyId": "AnonymousForClassmates",
               "ReflectQuestionId": "FeelingToday",
               "DueDateUtc": "2021-05-27T22:49:04.051Z",
               "ReflectFeedback": "Happy"
            }
         },
         "title": " ",
         "iconUrl": "https://roravi.ngrok.io/reflectCardImages/happyIcon.png"
      },
      {
         "type": "Action.Submit",
         "data": {
            "msteams": {
               "type": "task/fetch"
            },
            "data": {
               "Type": "task/fetch"
            },
            "datajson": {
               "PostCreatorName": "Fadi Teacher",
               "PostCreatorId": "c4e6beb4-5115-408d-8965-7328b0bfc6d4",
               "ReflectId": "8fcc02d7-1506-445c-b881-10649ff556b0",
               "Action": "setFeedback",
               "ReflectPrivacyId": "AnonymousForClassmates",
               "ReflectQuestionId": "FeelingToday",
               "DueDateUtc": "2021-05-27T22:49:04.051Z",
               "ReflectFeedback": "Neutral"
            }
         },
         "title": " ",
         "iconUrl": "https://roravi.ngrok.io/reflectCardImages/neutralIcon.png"
      },
      {
         "type": "Action.Submit",
         "data": {
            "msteams": {
               "type": "task/fetch"
            },
            "data": {
               "Type": "task/fetch"
            },
            "datajson": {
               "PostCreatorName": "Fadi Teacher",
               "PostCreatorId": "c4e6beb4-5115-408d-8965-7328b0bfc6d4",
               "ReflectId": "8fcc02d7-1506-445c-b881-10649ff556b0",
               "Action": "setFeedback",
               "ReflectPrivacyId": "AnonymousForClassmates",
               "ReflectQuestionId": "FeelingToday",
               "DueDateUtc": "2021-05-27T22:49:04.051Z",
               "ReflectFeedback": "Sad"
            }
         },
         "title": " ",
         "iconUrl": "https://roravi.ngrok.io/reflectCardImages/sadIcon.png"
      },
      {
         "type": "Action.Submit",
         "data": {
            "msteams": {
               "type": "task/fetch"
            },
            "data": {
               "Type": "task/fetch"
            },
            "datajson": {
               "PostCreatorName": "Fadi Teacher",
               "PostCreatorId": "c4e6beb4-5115-408d-8965-7328b0bfc6d4",
               "ReflectId": "8fcc02d7-1506-445c-b881-10649ff556b0",
               "Action": "setFeedback",
               "ReflectPrivacyId": "AnonymousForClassmates",
               "ReflectQuestionId": "FeelingToday",
               "DueDateUtc": "2021-05-27T22:49:04.051Z",
               "ReflectFeedback": "VerySad"
            }
         },
         "title": " ",
         "iconUrl": "https://roravi.ngrok.io/reflectCardImages/verySadIcon.png"
      },
      {
         "type": "Action.Submit",
         "data": {
            "msteams": {
               "type": "task/fetch"
            },
            "data": {
               "Type": "task/fetch"
            },
            "datajson": {
               "PostCreatorName": "Fadi Teacher",
               "PostCreatorId": "c4e6beb4-5115-408d-8965-7328b0bfc6d4",
               "ReflectId": "8fcc02d7-1506-445c-b881-10649ff556b0",
               "Action": "exploreFeedbacks",
               "ReflectPrivacyId": "AnonymousForClassmates",
               "ReflectQuestionId": "FeelingToday",
               "DueDateUtc": "2021-05-27T22:49:04.051Z",
               "ReflectFeedback": "None"
            }
         },
         "title": "Explore",
         "iconUrl": "https://roravi.ngrok.io/reflectCardImages/exploreReflectIcon.png"
      }
   ]
}
```

**Comment by anna-dingler** [comment]
I believe this issue is resolved by setting the `tooltip` property for each of the actions.

@JeanRoca Does this need to be updated on one of our samples?

**Comment by anna-dingler** [comment]
Resolving this issue because updating the card payload should fix the bug. Let me know if you need help with anything else!

**Comment by Fadi2019** [comment]
I am asking to reopen the bug since the issue is not solved
We are using the c# package and I cant change the json from there,

We use the c# sdk of teams adaptive card
The tooltip field is not implemented there.
we use this code in c#

new AdaptiveOpenUrlAction()
                        {
                            Title = " ",
                            IconUrl = $"../hostedContents/{veryPleasant}/$value",
                            Url = new Uri(reflectCardSettings.CardDeeplinks.VeryPleasantFeedbackButtonDeeplink),
                        },

no option for accessibility in this code
tooltip option is available by the json but not by the c# nuget, 
So I will ask you to reopen the bug for adaptive card guys to handle it in the c# nuget package and to add that ability of accessibility there.
The C# nuget link

**Comment by jwoo-msft** [comment]
> I am asking to reopen the bug since the issue is not solved We are using the c# package and I cant change the json from there,
> 
> We use the c# sdk of teams adaptive card The tooltip field is not implemented there. we use this code in c#
> 
> new AdaptiveOpenUrlAction() { Title = " ", IconUrl = $"../hostedContents/{veryPleasant}/$value", Url = new Uri(reflectCardSettings.CardDeeplinks.VeryPleasantFeedbackButtonDeeplink), },
> 
> no option for accessibility in this code tooltip option is available by the json but not by the c# nuget, So I will ask you to reopen the bug for adaptive card guys to handle it in the c# nuget package and to add that ability of accessibility there. The C# nuget link

Tooltip is recently implemented by this [PR](https://github.com/microsoft/AdaptiveCards/pull/8004). We will make a release in December.

**Comment by Fadi2019** [comment]
1. will be supported with c# (the nuget that you have for c#), I am using your c# nugest and the json format
2. I need the narrator to read it and not a tooltip

**Comment by jwoo-msft** [comment]
> 1. will be supported with c# (the nuget that you have for c#), I am using your c# nugest and the json format
> 2. I need the narrator to read it and not a tooltip
What does `it` referring to? Yes, AdaptiveCards nuget package will be released in Dec.
we don't have a firm plan to update AdaptiveCards.Rendering.Wpf nuget package to v1.5 as of yet. We will update AdaptiveCards.Rendering.Html package pretty soon.

**Comment by Fadi2019** [comment]
As the attached photo:
We have an adaptive card with buttons, each button has an icon inside it
In order to be accessible each photo/icon needs to have an alt attribute.
Alt attribute will help giving a label for the photo/icon so the narrator can read it

**Comment by jwoo-msft** [comment]
> As the attached photo: We have an adaptive card with buttons, each button has an icon inside it In order to be accessible each photo/icon needs to have an alt attribute. Alt attribute will help giving a label for the photo/icon so the narrator can read it

Renderers will set appropriate a11y label if tooltip or title are set in json. Since you're referring to AdaptiveCards.Rendering.Html nuget package. We haven't updated the nuget package or made the release. Since the feature is not yet implemented for the renderer; it's not a bug.

**Comment by RanaKh1** [comment]
Hi @jwoo-msft , is there an ETA for when it will be released to AdaptiveCards.Rendering.Html nuget package?

**Comment by NadRose** [comment]
Hi guys, Jumping in with some finding after a test:
The new `Tooltip` prop that is added in version 3.0.0 can be used in the C# nuget like in here:
![image](https://user-images.githubusercontent.com/28413152/228837692-7b333963-408b-4542-8a40-47401bbd5c1a.png)

But though it does change the `title` and `aria-description` attributes, It does not add an `alt` attribute, nor making the screen reader to announce that tooltip (tested in edge browser & windows narrator).
Hence, I will have to ask to re-open this bug and get your approval about this one.
Thank you.

**Comment by JeanRoca** [comment]
@jwoo-msft @anna-dingler is there a workaround that can be used for the case @NadRose is describing?

**Comment by anna-dingler** [comment]
Updated JSON:

```
{
   "type": "AdaptiveCard",
   "version": "0.0",
   "body": [
      {
         "type": "ColumnSet",
         "columns": [
            {
               "type": "Column",
               "items": [
                  {
                     "type": "TextBlock",
                     "size": "small",
                     "weight": "lighter",
                     "text": "Educators see your name and reflection, classmates won’t see your name",
                     "wrap": true,
                     "spacing": "none"
                  }
               ],
               "style": "emphasis",
               "bleed": true,
               "height": "stretch"
            }
         ]
      },
      {
         "type": "TextBlock",
         "size": "large",
         "weight": "bolder",
         "text": "How are you feeling today?",
         "wrap": true
      },
      {
         "type": "TextBlock",
         "size": "small",
         "text": "By Fadi Teacher  |  Closes {date}",
         "wrap": true
      }
   ],
   "actions": [
      {
         "type": "Action.Submit",
         "data": {
            "msteams": {
               "type": "task/fetch"
            },
            "data": {
               "Type": "task/fetch"
            },
            "datajson": {
               "PostCreatorName": "Fadi Teacher",
               "PostCreatorId": "c4e6beb4-5115-408d-8965-7328b0bfc6d4",
               "ReflectId": "8fcc02d7-1506-445c-b881-10649ff556b0",
               "Action": "setFeedback",
               "ReflectPrivacyId": "AnonymousForClassmates",
               "ReflectQuestionId": "FeelingToday",
               "DueDateUtc": "2021-05-27T22:49:04.051Z",
               "ReflectFeedback": "VeryHappy"
            }
         },
         "title": " ",
         "iconUrl": "https://roravi.ngrok.io/reflectCardImages/veryHappyIcon.png",
         "tooltip": "Very happy"
      },
      {
         "type": "Action.Submit",
         "data": {
            "msteams": {
               "type": "task/fetch"
            },
            "data": {
               "Type": "task/fetch"
            },
            "datajson": {
               "PostCreatorName": "Fadi Teacher",
               "PostCreatorId": "c4e6beb4-5115-408d-8965-7328b0bfc6d4",
               "ReflectId": "8fcc02d7-1506-445c-b881-10649ff556b0",
               "Action": "setFeedback",
               "ReflectPrivacyId": "AnonymousForClassmates",
               "ReflectQuestionId": "FeelingToday",
               "DueDateUtc": "2021-05-27T22:49:04.051Z",
               "ReflectFeedback": "Happy"
            }
         },
         "title": " ",
         "iconUrl": "https://roravi.ngrok.io/reflectCardImages/happyIcon.png",
         "tooltip": "Happy"
      },
      {
         "type": "Action.Submit",
         "data": {
            "msteams": {
               "type": "task/fetch"
            },
            "data": {
               "Type": "task/fetch"
            },
            "datajson": {
               "PostCreatorName": "Fadi Teacher",
               "PostCreatorId": "c4e6beb4-5115-408d-8965-7328b0bfc6d4",
               "ReflectId": "8fcc02d7-1506-445c-b881-10649ff556b0",
               "Action": "setFeedback",
               "ReflectPrivacyId": "AnonymousForClassmates",
               "ReflectQuestionId": "FeelingToday",
               "DueDateUtc": "2021-05-27T22:49:04.051Z",
               "ReflectFeedback": "Neutral"
            }
         },
         "title": " ",
         "iconUrl": "https://roravi.ngrok.io/reflectCardImages/neutralIcon.png",
         "tooltip": "Neutral"
      },
      {
         "type": "Action.Submit",
         "data": {
            "msteams": {
               "type": "task/fetch"
            },
            "data": {
               "Type": "task/fetch"
            },
            "datajson": {
               "PostCreatorName": "Fadi Teacher",
               "PostCreatorId": "c4e6beb4-5115-408d-8965-7328b0bfc6d4",
               "ReflectId": "8fcc02d7-1506-445c-b881-10649ff556b0",
               "Action": "setFeedback",
               "ReflectPrivacyId": "AnonymousForClassmates",
               "ReflectQuestionId": "FeelingToday",
               "DueDateUtc": "2021-05-27T22:49:04.051Z",
               "ReflectFeedback": "Sad"
            }
         },
         "title": " ",
         "iconUrl": "https://roravi.ngrok.io/reflectCardImages/sadIcon.png",
         "tooltip": "Sad"
      },
      {
         "type": "Action.Submit",
         "data": {
            "msteams": {
               "type": "task/fetch"
            },
            "data": {
               "Type": "task/fetch"
            },
            "datajson": {
               "PostCreatorName": "Fadi Teacher",
               "PostCreatorId": "c4e6beb4-5115-408d-8965-7328b0bfc6d4",
               "ReflectId": "8fcc02d7-1506-445c-b881-10649ff556b0",
               "Action": "setFeedback",
               "ReflectPrivacyId": "AnonymousForClassmates",
               "ReflectQuestionId": "FeelingToday",
               "DueDateUtc": "2021-05-27T22:49:04.051Z",
               "ReflectFeedback": "VerySad"
            }
         },
         "title": " ",
         "iconUrl": "https://roravi.ngrok.io/reflectCardImages/verySadIcon.png",
         "tooltip": "Very sad"
      },
      {
         "type": "Action.Submit",
         "data": {
            "msteams": {
               "type": "task/fetch"
            },
            "data": {
               "Type": "task/fetch"
            },
            "datajson": {
               "PostCreatorName": "Fadi Teacher",
               "PostCreatorId": "c4e6beb4-5115-408d-8965-7328b0bfc6d4",
               "ReflectId": "8fcc02d7-1506-445c-b881-10649ff556b0",
               "Action": "exploreFeedbacks",
               "ReflectPrivacyId": "AnonymousForClassmates",
               "ReflectQuestionId": "FeelingToday",
               "DueDateUtc": "2021-05-27T22:49:04.051Z",
               "ReflectFeedback": "None"
            }
         },
         "title": "Explore",
         "iconUrl": "https://roravi.ngrok.io/reflectCardImages/exploreReflectIcon.png",
         "tooltip": "Explore"
      }
   ]
}
```
